copy c:\tools\ironruby\Merlin\Main\Bin\Debug\IronRuby.dll %~dp0
copy c:\tools\ironruby\Merlin\Main\Bin\Debug\IronRuby.pdb %~dp0
copy c:\tools\ironruby\Merlin\Main\Bin\Debug\IronRuby.Libraries.dll %~dp0
copy c:\tools\ironruby\Merlin\Main\Bin\Debug\IronRuby.Libraries.pdb %~dp0
copy c:\tools\ironruby\Merlin\Main\Bin\Debug\IronRuby.Libraries.Yaml.dll %~dp0
copy c:\tools\ironruby\Merlin\Main\Bin\Debug\IronRuby.Libraries.Yaml.pdb %~dp0
copy c:\tools\ironruby\Merlin\Main\Bin\Debug\Microsoft.Scripting.dll %~dp0
copy c:\tools\ironruby\Merlin\Main\Bin\Debug\Microsoft.Scripting.pdb %~dp0
copy c:\tools\ironruby\Merlin\Main\Bin\Debug\Microsoft.Scripting.Core.dll %~dp0
copy c:\tools\ironruby\Merlin\Main\Bin\Debug\Microsoft.Scripting.Core.pdb %~dp0
copy c:\tools\ironruby\Merlin\Main\Bin\Debug\Microsoft.Scripting.ExtensionAttribute.dll %~dp0
copy c:\tools\ironruby\Merlin\Main\Bin\Debug\Microsoft.Scripting.ExtensionAttribute.pdb %~dp0
